language: node_js
node_js:
  - '12'
dist: trusty
sudo: required
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
    - node_modules
before_script:
  - sudo pip install coscmd
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run build
  - echo $ECS4_SSH_KEY > ecs4.pem
  - chmod 700 ecs4.pem
  - tar -czvf build.tar.gz dist/frontend
  - scp -i ecs4.pem -rf build.tar.gz ubuntu@ecs4.alpgo.cc:/home/ubuntu/demo_build/
  - ssh -i ecs4.pem ubuntu@ecs4.alpgo.cc 'bash -s' < build.sh $COS_SECRET_ID $COS_SECRET_KEY $COS_BUCKET_NAME $COS_BUCKET_REGION
